name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
   
    - name: Set up python
      uses: aparnajyothi-y/setup-python@Feature-request#476
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: ./requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash






